#!/bin/bash

source /post/config


#HOSTNAME
echo "creami" > /etc/hostname &&


## LOCALTIME 
ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime &&
hwclock --systohc &&
timedatectl set-ntp true &&
timedatectl set-timezone $TIMEZONE &&


## CONFIG
#cp -fr /post/base/* / &&


## LOCALE
locale-gen &&


##
## BOOTUPS
mkdir -p /boot/{efi,kernel,creamy} &&
mkdir -p /boot/efi/{boot,linux,systemd,rescue} &&
mv /boot/*-ucode.img /boot/kernel/ &&
rm /etc/mkinitcpio.conf &&
rm -fr /etc/mkinitcpio.conf.d/ &&


## KERNELS
curl -s 'https://liquorix.net/install-liquorix.sh' | sudo bash &&



## EMULATOR

## switch
wget -O /usr/rbin/switch.AppImage https://git.ryujinx.app/api/v4/projects/1/packages/generic/Ryubing/1.3.3/ryujinx-1.3.3-x64.AppImage &&
chmod +x /usr/rbin/switch.AppImage && 

## heroic
wget -O /usr/rbin/heroic.AppImage https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.18.1/Heroic-2.18.1-linux-x86_64.AppImage &&
chmod +x /usr/rbin/heroic.AppImage  &&

## playstation 1
wget -O /usr/rbin/plays1.AppImage https://github.com/stenzek/duckstation/releases/download/latest/DuckStation-x64.AppImage &&
chmod +x /usr/rbin/plays1.AppImage &&

## playstation 2
wget -O /usr/rbin/plays2.AppImage https://github.com/PCSX2/pcsx2/releases/download/v2.4.0/pcsx2-v2.4.0-linux-appimage-x64-Qt.AppImage &&
chmod +x /usr/rbin/plays2.AppImage &&

## playstation 3
wget -O /usr/rbin/plays3.AppImage https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-c669a0beb721d704241980675154cb35b0221d92/rpcs3-v0.0.38-18364-c669a0be_linux64.AppImage &&
chmod +x /usr/rbin/plays3.AppImage &&

## xbox 360
wget -O /usr/rbin/xbox36.AppImage https://github.com/xemu-project/xemu/releases/download/v0.8.115/xemu-v0.8.115-x86_64.AppImage &&
chmod +x /usr/rbin/xbox36.AppImage && 



##
## SERVICE
systemctl enable sddm &&
systemctl enable dnsmasq &&
systemctl enable sshd &&
systemctl enable update.timer &&
systemctl enable firewalld &&
systemctl enable NetworkManager &&
systemctl enable --global pipewire-pulse &&
systemctl enable systemd-timesyncd.service &&


##
## BINPATH
chmod +x /usr/xbin/* &&
chmod +x /usr/rbin/* &&


##
## SESSION
rm /usr/share/wayland-sessions/weston.desktop &&



## BOOTING
echo "root=$DISKPROC" > /etc/cmdline.d/01-boot.conf &&
mkinitcpio -P &&


## GRUBERS
echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub && 
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=creamy &&
grub-mkconfig -o /boot/grub/grub.cfg &&


## USERADD
useradd -m $USERNAME &&
usermod -aG wheel $USERNAME &&
echo "add user password" &&
passwd $USERNAME &&


echo "installation finish, close chroot"